# -*- coding: utf-8 -*-
"""GlobalDataAnalytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-IvZC4iI0qryh1f7Zo_Qgis8JlvSup0e
"""

# Commented out IPython magic to ensure Python compatibility.
import math
import seaborn as sns
sns.set(style="whitegrid", color_codes=True)


from wordcloud import WordCloud, STOPWORDS

import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np # linear algebra
import matplotlib
import matplotlib.pyplot as plt
import sklearn
# %matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = [16, 12]
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

from subprocess import check_output
#print(check_output(["ls", "../input"]).decode("utf8"))



# Any results you write to the current directory are saved as output.
#filenames = check_output(["ls", "../input"]).decode("utf8").strip()

df = pd.read_excel("/Online Retail.xlsx")
print(df.dtypes)
df.head()

varnames = df.columns.values

for varname in varnames:
    if df[varname].dtype == 'object':
        lst = df[varname].unique()
        print(varname + " : " + str(len(lst)) + " values such as " + str(lst))

sns.pairplot(x_vars = ['UnitPrice'],y_vars=['Quantity'], hue = 'Country', data = df, size = 10);

df['InvoiceNo'].str

df['SalesAmount'] = df['UnitPrice'] * df['Quantity']

df.plot(x = 'InvoiceDate', y = 'SalesAmount')

df['Country'].value_counts()

countryNames = df['Country'].unique()

def tsplot(country):
    dg = df[df['Country'] == country]
    dg.plot(x = 'InvoiceDate', y = 'SalesAmount')

tsplot('United Kingdom')

tsplot('Germany')

df.sort_values(by='SalesAmount', ascending=False)

df['QuantityAbs'] = df['Quantity'].apply(math.fabs)
df['UnitPriceAbs'] = df['UnitPrice'].apply(math.fabs)

df.sort_values(by='UnitPriceAbs', ascending=True)

df.sort_values(by='UnitPriceAbs', ascending=False)

df.sort_values(by='QuantityAbs', ascending=False)

df.sort_values(by='QuantityAbs', ascending=True)

stopwords = set(STOPWORDS)

wordcloud = WordCloud(
                          background_color='white',
                          stopwords=stopwords,
                          max_words=200,
                          max_font_size=40,
                          random_state=42
                         ).generate(str(df['Description']))

print(wordcloud)
fig = plt.figure(1)
plt.imshow(wordcloud)
plt.axis('off')
plt.show()
fig.savefig("itemDescriptionCloud.png", dpi=900)

sns.distplot(df['UnitPrice'])

sns.distplot(df['Quantity'])

sns.distplot(df['QuantityAbs'])

